# Generated by Django 5.1.4 on 2026-01-07 20:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('users', '0010_add_user_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyScope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique scope identifier (e.g., "dicom:read", "ai:submit")', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(help_text='What this scope allows')),
                ('category', models.CharField(choices=[('dicom', 'DICOM Operations'), ('ai', 'AI Analysis'), ('users', 'User Management'), ('admin', 'Administrative')], db_index=True, help_text='Scope category', max_length=50)),
                ('allowed_endpoints', models.JSONField(default=list, help_text='List of URL patterns this scope grants access to')),
                ('allowed_methods', models.JSONField(default=list, help_text='Allowed HTTP methods (GET, POST, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scope is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key Scope',
                'verbose_name_plural': 'API Key Scopes',
                'db_table': 'credentials_api_key_scopes',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnhancedAPIKey',
            fields=[
                ('api_key', models.OneToOneField(help_text='Associated UserAPIKey', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enhanced', serialize=False, to='users.userapikey')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Maximum requests per minute (0 = unlimited)')),
                ('rate_limit_per_hour', models.IntegerField(default=3600, help_text='Maximum requests per hour (0 = unlimited)')),
                ('rate_limit_per_day', models.IntegerField(default=86400, help_text='Maximum requests per day (0 = unlimited)')),
                ('current_minute_count', models.IntegerField(default=0, help_text='Current minute request count')),
                ('current_hour_count', models.IntegerField(default=0, help_text='Current hour request count')),
                ('current_day_count', models.IntegerField(default=0, help_text='Current day request count')),
                ('quota_reset_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When quotas were last reset')),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total requests made with this key')),
                ('last_request_at', models.DateTimeField(blank=True, help_text='Timestamp of last request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scopes', models.ManyToManyField(blank=True, help_text='Permissions granted to this API key', related_name='api_keys', to='credentials.apikeyscope')),
            ],
            options={
                'verbose_name': 'Enhanced API Key',
                'verbose_name_plural': 'Enhanced API Keys',
                'db_table': 'credentials_enhanced_api_keys',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('jwt', 'JWT Token'), ('api_key', 'API Key')], db_index=True, default='jwt', help_text='Type of authentication used', max_length=20)),
                ('user_agent', models.TextField(blank=True, help_text='Full User-Agent header')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('api', 'API/Automated'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Detected device type', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address')),
                ('ip_country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('ip_city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Session creation timestamp')),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Last activity timestamp')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Session expiration timestamp')),
                ('terminated_at', models.DateTimeField(blank=True, help_text='Session termination timestamp', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether session is currently active')),
                ('termination_reason', models.CharField(blank=True, choices=[('logout', 'User Logout'), ('expired', 'Token Expired'), ('revoked', 'Manually Revoked'), ('concurrent_limit', 'Concurrent Session Limit'), ('security', 'Security Issue Detected')], help_text='Reason for session termination', max_length=50)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Flagged by anomaly detection')),
                ('suspicious_reason', models.TextField(blank=True, help_text='Reason for suspicious flag')),
                ('outstanding_token', models.OneToOneField(blank=True, help_text='Associated JWT token (null for API key sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_tracking', to='token_blacklist.outstandingtoken')),
                ('user', models.ForeignKey(help_text='User that owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'credentials_user_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username_attempted', models.CharField(blank=True, help_text='Email/username used in attempt (even if user not found)', max_length=255)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('token_expired', 'Token Expired'), ('token_blacklisted', 'Token Blacklisted'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('apikey_auth', 'API Key Authentication'), ('apikey_created', 'API Key Created'), ('apikey_revoked', 'API Key Revoked'), ('apikey_expired', 'API Key Expired'), ('session_created', 'Session Created'), ('session_terminated', 'Session Terminated'), ('concurrent_session_limit', 'Concurrent Session Limit Hit'), ('suspicious_activity', 'Suspicious Activity Detected'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('invalid_token', 'Invalid Token Used'), ('scope_violation', 'API Key Scope Violation')], db_index=True, help_text='Type of event', max_length=50)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('request_path', models.CharField(blank=True, help_text='API endpoint path', max_length=255)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data')),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Event flagged as suspicious')),
                ('risk_score', models.IntegerField(default=0, help_text='Calculated risk score (0-100)')),
                ('user', models.ForeignKey(blank=True, help_text='User involved in the event (null for failed logins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Associated session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='credentials.usersession')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'credentials_audit_logs',
                'ordering': ['-event_timestamp'],
                'permissions': [('view_audit_logs', 'Can view audit logs'), ('export_audit_logs', 'Can export audit logs')],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the request was made')),
                ('request_path', models.CharField(db_index=True, help_text='API endpoint accessed', max_length=255)),
                ('request_method', models.CharField(help_text='HTTP method', max_length=10)),
                ('response_status', models.IntegerField(help_text='HTTP response status code')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('request_size_bytes', models.IntegerField(default=0, help_text='Request body size in bytes')),
                ('response_size_bytes', models.IntegerField(default=0, help_text='Response body size in bytes')),
                ('scope_matched', models.CharField(blank=True, help_text='Which scope was used for this request', max_length=100)),
                ('rate_limited', models.BooleanField(db_index=True, default=False, help_text='Whether this request was rate limited')),
                ('api_key', models.ForeignKey(help_text='API key that made the request', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.userapikey')),
            ],
            options={
                'verbose_name': 'API Key Usage Log',
                'verbose_name_plural': 'API Key Usage Logs',
                'db_table': 'credentials_api_key_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', '-timestamp'], name='credentials_api_key_8da65e_idx'), models.Index(fields=['request_path', '-timestamp'], name='credentials_request_405349_idx'), models.Index(fields=['-timestamp'], name='credentials_timesta_efc02d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='credentials_user_id_a83cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'ip_address'], name='credentials_user_id_c43215_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['-last_activity_at'], name='credentials_last_ac_69c2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_suspicious', '-created_at'], name='credentials_is_susp_7d983d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-event_timestamp'], name='credentials_user_id_da1ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', '-event_timestamp'], name='credentials_event_t_1e7c73_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-event_timestamp'], name='credentials_ip_addr_1562a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_suspicious', '-event_timestamp'], name='credentials_is_susp_331cbf_idx'),
        ),
    ]
