# Generated by Django 5.1.4 on 2026-01-08 07:57

from django.db import migrations


def populate_default_scopes(apps, schema_editor):
    """
    Create default API key scopes and migrate existing API keys.
    """
    APIKeyScope = apps.get_model('credentials', 'APIKeyScope')
    EnhancedAPIKey = apps.get_model('credentials', 'EnhancedAPIKey')
    UserAPIKey = apps.get_model('users', 'UserAPIKey')

    # Create default scopes
    scopes = [
        {
            'name': 'full_access',
            'display_name': 'Full API Access',
            'description': 'Unrestricted access to all API endpoints (default for existing keys)',
            'category': 'admin',
            'allowed_endpoints': [r'^/api/.*'],
            'allowed_methods': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
            'is_active': True,
        },
        {
            'name': 'dicom:read',
            'display_name': 'DICOM Read Access',
            'description': 'Read-only access to DICOM endpoints',
            'category': 'dicom',
            'allowed_endpoints': [r'^/api/dicom/.*', r'^/api/dicom-images/.*', r'^/api/dicom-gateway/.*'],
            'allowed_methods': ['GET', 'HEAD', 'OPTIONS'],
            'is_active': True,
        },
        {
            'name': 'dicom:write',
            'display_name': 'DICOM Write Access',
            'description': 'Full access to DICOM endpoints (read and write)',
            'category': 'dicom',
            'allowed_endpoints': [r'^/api/dicom/.*', r'^/api/dicom-images/.*'],
            'allowed_methods': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
            'is_active': True,
        },
        {
            'name': 'ai:submit',
            'display_name': 'AI Analysis Submission',
            'description': 'Submit AI analysis jobs',
            'category': 'ai',
            'allowed_endpoints': [r'^/api/ai-analysis/submit/.*', r'^/api/ai-analysis/models/.*'],
            'allowed_methods': ['GET', 'POST', 'HEAD', 'OPTIONS'],
            'is_active': True,
        },
        {
            'name': 'ai:view',
            'display_name': 'AI Analysis Viewing',
            'description': 'View AI analysis results',
            'category': 'ai',
            'allowed_endpoints': [r'^/api/ai-analysis/.*'],
            'allowed_methods': ['GET', 'HEAD', 'OPTIONS'],
            'is_active': True,
        },
        {
            'name': 'users:view',
            'display_name': 'User Viewing',
            'description': 'View user profile and information',
            'category': 'users',
            'allowed_endpoints': [r'^/api/users/profile/.*', r'^/api/users/me/.*'],
            'allowed_methods': ['GET', 'HEAD', 'OPTIONS'],
            'is_active': True,
        },
    ]

    # Create scopes
    created_scopes = {}
    for scope_data in scopes:
        scope, created = APIKeyScope.objects.get_or_create(
            name=scope_data['name'],
            defaults=scope_data
        )
        created_scopes[scope_data['name']] = scope
        if created:
            print(f"Created scope: {scope_data['name']}")

    # Get full_access scope
    full_access_scope = created_scopes.get('full_access')

    if not full_access_scope:
        print("Warning: full_access scope not created")
        return

    # Migrate existing UserAPIKey instances
    existing_keys = UserAPIKey.objects.all()
    migrated_count = 0

    for user_api_key in existing_keys:
        # Create EnhancedAPIKey if it doesn't exist
        enhanced_key, created = EnhancedAPIKey.objects.get_or_create(
            api_key=user_api_key,
            defaults={
                'rate_limit_per_minute': 60,
                'rate_limit_per_hour': 3600,
                'rate_limit_per_day': 86400,
            }
        )

        if created:
            # Assign full_access scope to maintain backward compatibility
            enhanced_key.scopes.add(full_access_scope)
            migrated_count += 1
            print(f"Migrated API key: {user_api_key.key_prefix} with full_access scope")

    print(f"Migration complete: {migrated_count} API keys migrated with full_access scope")


def reverse_populate_scopes(apps, schema_editor):
    """
    Reverse migration - remove all scopes.
    """
    APIKeyScope = apps.get_model('credentials', 'APIKeyScope')
    EnhancedAPIKey = apps.get_model('credentials', 'EnhancedAPIKey')

    # Delete all enhanced API keys
    EnhancedAPIKey.objects.all().delete()

    # Delete all scopes
    APIKeyScope.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('users', '0010_add_user_api_key'),
    ]

    operations = [
        migrations.RunPython(populate_default_scopes, reverse_populate_scopes),
    ]
