# Generated by Django 5.2.17 on 2026-09-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='sid',
            field=models.CharField(blank=True, db_index=True, help_text='Session id claim shared by every token in a rotation chain', max_length=64),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('logout', 'User Logout'), ('expired', 'Token Expired'), ('revoked', 'Manually Revoked'), ('concurrent_limit', 'Concurrent Session Limit'), ('idle_timeout', 'Idle Timeout'), ('security', 'Security Issue Detected')], help_text='Reason for session termination', max_length=50),
        ),
    ]
