"""
DICOM CD / USB export.

Builds a standards-style DICOM media ZIP for a study:
  - Preferred: a pydicom ``FileSet`` (generates a conformant DICOMDIR plus the
    renamed instance files), the layout burners expect for patient CDs.
  - Fallback: if any instance can't be added to the FileSet (non-conformant or
    unreadable file), fall back to a plain ``DICOM/`` folder containing the raw
    files plus a README — still readable by every DICOM viewer.

Synchronous by design: veterinary studies are typically a handful of CR/DX
images. Revisit with a Celery task + polling if multi-hundred-MB CT studies
become common.
"""

import logging
import os
import tempfile
import zipfile
from io import BytesIO

logger = logging.getLogger(__name__)

README_TEXT = """DICOM study export
===================

This archive contains the DICOM files for one imaging study.

- If a DICOMDIR file is present at the root, the archive follows the DICOM
  media (PS3.10) layout and can be burned to CD/USB directly.
- Otherwise the files are in the DICOM/ folder and can be opened with any
  DICOM viewer (e.g. Horos, MicroDicom, OHIF).

Generated by VetImage.
"""


def build_cd_zip(study) -> BytesIO:
    """Return a BytesIO ZIP of the study's DICOM files (DICOMDIR when possible)."""
    from dicom_images.models import MedicalImage

    images = list(
        MedicalImage.objects.filter(series__study=study).select_related('series')
    )

    buffer = BytesIO()
    with tempfile.TemporaryDirectory() as tmpdir:
        wrote_fileset = _try_write_fileset(images, tmpdir)
        if not wrote_fileset:
            _write_plain_tree(images, tmpdir)

        with open(os.path.join(tmpdir, 'README.txt'), 'w') as fh:
            fh.write(README_TEXT)

        with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
            for root, _dirs, files in os.walk(tmpdir):
                for fname in files:
                    full = os.path.join(root, fname)
                    zf.write(full, os.path.relpath(full, tmpdir))

    buffer.seek(0)
    return buffer


def _try_write_fileset(images, tmpdir) -> bool:
    """Attempt a conformant DICOMDIR FileSet. Returns False on any failure."""
    if not images:
        return False
    try:
        from pydicom import dcmread
        from pydicom.fileset import FileSet

        fs = FileSet()
        for img in images:
            fs.add(dcmread(img.file.path))
        fs.write(tmpdir)
        return True
    except Exception as exc:  # non-conformant instance, missing attrs, etc.
        logger.info('FileSet export failed (%s); falling back to plain tree.', exc)
        # Clear anything FileSet may have partially written.
        for root, dirs, files in os.walk(tmpdir, topdown=False):
            for f in files:
                os.unlink(os.path.join(root, f))
            for d in dirs:
                os.rmdir(os.path.join(root, d))
        return False


def _write_plain_tree(images, tmpdir):
    """Plain DICOM/<series>/<n>.dcm layout — universally viewer-readable."""
    base = os.path.join(tmpdir, 'DICOM')
    os.makedirs(base, exist_ok=True)
    for idx, img in enumerate(images, start=1):
        series_dir = os.path.join(base, f'SER{img.series_id or 0:04d}')
        os.makedirs(series_dir, exist_ok=True)
        dest = os.path.join(series_dir, f'IMG{idx:05d}.dcm')
        try:
            with img.file.open('rb') as src, open(dest, 'wb') as dst:
                dst.write(src.read())
        except Exception as exc:
            logger.warning('Skipping unreadable image %s: %s', img.pk, exc)
