# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import orchestrator_pb2 as orchestrator__pb2


class OrchestratorServiceStub(object):
    """==============================================================================
    Orchestrator Service - Web App → Orchestrator Communication
    ==============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/SubmitJob',
                request_serializer=orchestrator__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.SubmitJobResponse.FromString,
                )
        self.GetJobStatus = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/GetJobStatus',
                request_serializer=orchestrator__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.JobStatusResponse.FromString,
                )
        self.StreamJobStatus = channel.unary_stream(
                '/orchestrator.v1.OrchestratorService/StreamJobStatus',
                request_serializer=orchestrator__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.JobStatusResponse.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/ListModels',
                request_serializer=orchestrator__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ListModelsResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/HealthCheck',
                request_serializer=orchestrator__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.HealthCheckResponse.FromString,
                )


class OrchestratorServiceServicer(object):
    """==============================================================================
    Orchestrator Service - Web App → Orchestrator Communication
    ==============================================================================

    """

    def SubmitJob(self, request, context):
        """Submit inference job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobStatus(self, request, context):
        """Stream job status updates (for real-time UI)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List available models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=orchestrator__pb2.SubmitJobRequest.FromString,
                    response_serializer=orchestrator__pb2.SubmitJobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=orchestrator__pb2.GetJobStatusRequest.FromString,
                    response_serializer=orchestrator__pb2.JobStatusResponse.SerializeToString,
            ),
            'StreamJobStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobStatus,
                    request_deserializer=orchestrator__pb2.GetJobStatusRequest.FromString,
                    response_serializer=orchestrator__pb2.JobStatusResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=orchestrator__pb2.ListModelsRequest.FromString,
                    response_serializer=orchestrator__pb2.ListModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=orchestrator__pb2.HealthCheckRequest.FromString,
                    response_serializer=orchestrator__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """==============================================================================
    Orchestrator Service - Web App → Orchestrator Communication
    ==============================================================================

    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.OrchestratorService/SubmitJob',
            orchestrator__pb2.SubmitJobRequest.SerializeToString,
            orchestrator__pb2.SubmitJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.OrchestratorService/GetJobStatus',
            orchestrator__pb2.GetJobStatusRequest.SerializeToString,
            orchestrator__pb2.JobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orchestrator.v1.OrchestratorService/StreamJobStatus',
            orchestrator__pb2.GetJobStatusRequest.SerializeToString,
            orchestrator__pb2.JobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.OrchestratorService/ListModels',
            orchestrator__pb2.ListModelsRequest.SerializeToString,
            orchestrator__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.OrchestratorService/HealthCheck',
            orchestrator__pb2.HealthCheckRequest.SerializeToString,
            orchestrator__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
