# Generated by Django 5.1.4 on 2026-01-05 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_running', models.BooleanField(default=True)),
                ('scp_status', models.CharField(default='running', max_length=20)),
                ('api_status', models.CharField(default='running', max_length=20)),
                ('cpu_percent', models.FloatField()),
                ('memory_used_gb', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('disk_free_gb', models.FloatField()),
                ('disk_used_percent', models.FloatField()),
                ('total_received', models.IntegerField(default=0)),
                ('total_success', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=100.0)),
                ('active_associations', models.IntegerField(default=0)),
                ('queue_depth', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gateway Health Metric',
                'verbose_name_plural': 'Gateway Health Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dicom_gatew_timesta_e34cfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='PACSConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this PACS', max_length=200)),
                ('ae_title', models.CharField(help_text='DICOM Application Entity Title', max_length=16, unique=True)),
                ('host', models.CharField(help_text='PACS hostname or IP address', max_length=255)),
                ('port', models.IntegerField(default=11112, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('max_pdu_length', models.IntegerField(default=16384)),
                ('timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds')),
                ('tls_enabled', models.BooleanField(default=False)),
                ('tls_cert_path', models.CharField(blank=True, max_length=500)),
                ('allowed_source_ips', models.JSONField(default=list, help_text='List of allowed source IP addresses')),
                ('auto_retrieve_enabled', models.BooleanField(default=False, help_text='Automatically retrieve studies from this PACS')),
                ('auto_analyze_enabled', models.BooleanField(default=False, help_text='Automatically trigger AI analysis for received studies')),
                ('default_model_key', models.CharField(blank=True, help_text='Default AI model for auto-analysis', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pacs_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PACS Configuration',
                'verbose_name_plural': 'PACS Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(max_length=50)),
                ('source_ip', models.GenericIPAddressField()),
                ('event_type', models.CharField(choices=[('dicom.receive', 'DICOM Image Received'), ('dicom.send', 'DICOM Image Sent'), ('phi.access', 'PHI Accessed'), ('phi.export', 'PHI Exported'), ('config.change', 'Configuration Changed'), ('pacs.connect', 'PACS Connection'), ('pacs.disconnect', 'PACS Disconnection'), ('analysis.create', 'Analysis Task Created'), ('security.unauthorized', 'Unauthorized Access Attempt')], db_index=True, max_length=50)),
                ('action_description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('component', models.CharField(choices=[('gateway', 'DICOM Gateway'), ('backend', 'Backend API'), ('frontend', 'Frontend')], max_length=50)),
                ('study_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('patient_id_hash', models.CharField(blank=True, max_length=64)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='dicom_gatew_timesta_0c5f0c_idx'), models.Index(fields=['user', '-timestamp'], name='dicom_gatew_user_id_492f52_idx'), models.Index(fields=['study_uid', '-timestamp'], name='dicom_gatew_study_u_411a48_idx'), models.Index(fields=['success', '-timestamp'], name='dicom_gatew_success_aa253f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DICOMTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('C-STORE', 'Store'), ('C-FIND', 'Find'), ('C-MOVE', 'Move'), ('C-GET', 'Get'), ('C-ECHO', 'Echo')], db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, max_length=10)),
                ('source_ae', models.CharField(max_length=16)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('dest_ae', models.CharField(max_length=16)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=64)),
                ('series_instance_uid', models.CharField(blank=True, max_length=64)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=64)),
                ('patient_id_hash', models.CharField(db_index=True, help_text='SHA-256 hash of Patient ID (for privacy)', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(help_text='Duration in milliseconds', null=True)),
                ('file_size_bytes', models.BigIntegerField(null=True)),
                ('modality', models.CharField(blank=True, db_index=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pacs_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dicom_gateway.pacsconfiguration')),
            ],
            options={
                'verbose_name': 'DICOM Transaction',
                'verbose_name_plural': 'DICOM Transactions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at', 'status'], name='dicom_gatew_started_f24479_idx'), models.Index(fields=['study_instance_uid', 'transaction_type'], name='dicom_gatew_study_i_8b3156_idx'), models.Index(fields=['patient_id_hash', '-started_at'], name='dicom_gatew_patient_8973b0_idx')],
            },
        ),
    ]
