# Generated by Django 5.1.4 on 2026-01-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomtransaction',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
