# Generated by Django 5.1.4 on 2026-01-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_gateway', '0002_allow_null_error_message'),
        ('users', '0009_add_profile_org_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pacsconfiguration',
            name='receiving_organization',
            field=models.ForeignKey(blank=True, help_text='Organization override (optional). If not set, uses receiving_user.profile.organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_configs', to='users.organization'),
        ),
        migrations.AddField(
            model_name='pacsconfiguration',
            name='receiving_user',
            field=models.ForeignKey(blank=True, help_text='User to attribute incoming DICOM transfers from this PACS. If not set, transfers will use the gateway service account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_pacs_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
