# Generated by Django 5.1.4 on 2026-01-07 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_gateway', '0003_add_pacs_user_mapping'),
        ('users', '0010_add_user_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacsconfiguration',
            name='receiving_user',
        ),
        migrations.AddField(
            model_name='pacsconfiguration',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of this PACS system and its purpose'),
        ),
        migrations.AddField(
            model_name='pacsconfiguration',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='PACS manufacturer (e.g., "GE Healthcare", "Siemens", "Philips")', max_length=100),
        ),
        migrations.AddField(
            model_name='pacsconfiguration',
            name='node',
            field=models.CharField(blank=True, help_text='DICOM node name - distinct identifier from AE Title for routing purposes', max_length=100),
        ),
        migrations.AddField(
            model_name='pacsconfiguration',
            name='node_user',
            field=models.ForeignKey(blank=True, help_text='User whose API key will be used for authenticating DICOM uploads from this PACS. If not set, transfers will use the gateway service account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_node_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pacsconfiguration',
            name='receiving_organization',
            field=models.ForeignKey(blank=True, help_text='Organization override (optional). If not set, uses node_user.profile.organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_configs', to='users.organization'),
        ),
    ]
