# Generated by Django 5.2.17 on 2026-09-01 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_gateway', '0005_rename_organization_to_clinic'),
        ('users', '0015_rename_users_clini_name_idx_users_clini_name_ec26e6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacsconfiguration',
            name='receiving_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic override (optional). If not set, uses node_user.profile.clinic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_configs', to='users.clinic'),
        ),
    ]
