"""
Pet Passport / Travel Health Certificate PDF generator.

Produces an EU-Pet-Passport-style document for an AnimalPatient: owner
contact, animal signalment, microchip number, full vaccination history and a
veterinarian signature block. Built with ReportLab, following the style of
reports/services/pdf_generator.py.

This document supports travel/identification paperwork; it is not itself an
official government document — the clinic vet signs and stamps the printout.
"""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

ACCENT = colors.HexColor('#1e3a5f')


class PassportPDFGenerator:
    """Generates a pet passport PDF from an AnimalPatient instance."""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.styles.add(ParagraphStyle(
            'PassportTitle',
            parent=self.styles['Title'],
            fontSize=18,
            spaceAfter=2 * mm,
            textColor=ACCENT,
        ))
        self.styles.add(ParagraphStyle(
            'PassportSubtitle',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.gray,
            spaceAfter=5 * mm,
        ))
        self.styles.add(ParagraphStyle(
            'PassportSection',
            parent=self.styles['Heading2'],
            fontSize=12,
            spaceBefore=5 * mm,
            spaceAfter=2 * mm,
            textColor=ACCENT,
        ))
        self.styles.add(ParagraphStyle(
            'PassportFooter',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
            spaceBefore=6 * mm,
        ))

    # ------------------------------------------------------------------

    def generate(self, animal):
        """Return a BytesIO buffer with the passport PDF for ``animal``."""
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            topMargin=18 * mm,
            bottomMargin=18 * mm,
            leftMargin=18 * mm,
            rightMargin=18 * mm,
            title=f'Pet Passport — {animal.name}',
        )

        story = []
        story.append(Paragraph('Pet Health Passport', self.styles['PassportTitle']))
        story.append(Paragraph(
            'Identification & vaccination record — to be validated by the issuing veterinarian',
            self.styles['PassportSubtitle'],
        ))
        story.append(HRFlowable(width='100%', color=ACCENT, thickness=1))

        story += self._owner_section(animal.owner)
        story += self._animal_section(animal)
        story += self._vaccination_section(animal)
        story += self._signature_section()

        story.append(Paragraph(
            'Generated by VetImage. This printout becomes valid only when signed and '
            'stamped by a licensed veterinarian. It is not an official government document.',
            self.styles['PassportFooter'],
        ))

        doc.build(story)
        buffer.seek(0)
        return buffer

    # ------------------------------------------------------------------

    def _kv_table(self, rows):
        """Two-column label/value table used for owner + animal sections."""
        table = Table(rows, colWidths=[55 * mm, 115 * mm])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (0, -1), ACCENT),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
            ('TOPPADDING', (0, 0), (-1, -1), 2),
        ]))
        return table

    def _owner_section(self, owner):
        rows = [
            ['Owner', f'{owner.first_name} {owner.last_name}'],
            ['Email', owner.email or '—'],
            ['Phone', owner.phone or '—'],
            ['Address', ', '.join(filter(None, [owner.address, owner.city, owner.country])) or '—'],
        ]
        return [
            Paragraph('I. Owner', self.styles['PassportSection']),
            self._kv_table(rows),
        ]

    def _animal_section(self, animal):
        rows = [
            ['Name', animal.name],
            ['Species', animal.get_species_display()],
            ['Breed', animal.breed or '—'],
            ['Sex', animal.get_sex_display() if animal.sex else '—'],
            ['Date of birth', animal.date_of_birth.isoformat() if animal.date_of_birth else '—'],
            ['Colour / markings', animal.color or '—'],
            ['Microchip number', animal.microchip_id or '—'],
        ]
        if animal.insurance_provider:
            policy = animal.insurance_policy_number or '—'
            rows.append(['Insurance', f'{animal.insurance_provider} ({policy})'])
        return [
            Paragraph('II. Animal', self.styles['PassportSection']),
            self._kv_table(rows),
        ]

    def _vaccination_section(self, animal):
        header = ['Vaccine', 'Administered', 'Valid until', 'Batch', 'Veterinarian']
        rows = [header]
        for v in animal.vaccinations.all().order_by('-administered_on'):
            vet = v.administered_by.email if v.administered_by else '—'
            rows.append([
                v.vaccine_name,
                v.administered_on.isoformat(),
                v.next_due_on.isoformat() if v.next_due_on else '—',
                v.batch_number or '—',
                vet,
            ])
        if len(rows) == 1:
            rows.append(['No vaccinations recorded', '', '', '', ''])

        table = Table(rows, colWidths=[40 * mm, 28 * mm, 28 * mm, 30 * mm, 44 * mm], repeatRows=1)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f1f5f9')]),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))
        return [
            Paragraph('III. Vaccination Record', self.styles['PassportSection']),
            table,
        ]

    def _signature_section(self):
        rows = [
            ['Veterinarian (name, licence no.)', ''],
            ['Clinic', ''],
            ['Date', ''],
            ['Signature & stamp', ''],
        ]
        table = Table(rows, colWidths=[55 * mm, 115 * mm], rowHeights=[10 * mm, 10 * mm, 10 * mm, 22 * mm])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (0, -1), ACCENT),
            ('LINEBELOW', (1, 0), (1, -1), 0.5, colors.HexColor('#94a3b8')),
            ('VALIGN', (0, 0), (-1, -1), 'BOTTOM'),
        ]))
        return [
            Paragraph('IV. Veterinarian Validation', self.styles['PassportSection']),
            Spacer(1, 2 * mm),
            table,
        ]
