# Generated by Django 5.1.4 on 2025-12-25 11:29

import ai_analysis.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicom_images', '0002_medicalimage_dicom_tags_medicalimage_max_pixel_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'MIRAGE v1.0')", max_length=100)),
                ('key', models.CharField(db_index=True, help_text="Unique identifier for API usage (e.g., 'mirage-v1')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the model's capabilities")),
                ('version', models.CharField(help_text='Model version number', max_length=20)),
                ('endpoint_url', models.URLField(help_text="Base URL of the AI service (e.g., 'http://mirage-service:8000')")),
                ('connector_class', models.CharField(help_text="Python path to connector class (e.g., 'ai_analysis.connectors.mirage.MirageConnector')", max_length=200)),
                ('model_type', models.CharField(choices=[('registration', 'Image Registration'), ('segmentation', 'Image Segmentation'), ('classification', 'Image Classification'), ('detection', 'Object Detection'), ('reconstruction', '3D Reconstruction'), ('other', 'Other')], default='other', help_text='Type of AI model', max_length=50)),
                ('supported_modalities', models.JSONField(default=list, help_text="List of supported DICOM modalities (e.g., ['MR', 'CT'])")),
                ('required_parameters', models.JSONField(default=dict, help_text='JSON schema of required parameters for this model')),
                ('default_parameters', models.JSONField(default=dict, help_text='Default parameter values')),
                ('timeout_seconds', models.IntegerField(default=1800, help_text='Maximum processing time in seconds (default: 30 minutes)')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts for failed tasks')),
                ('retry_delay_seconds', models.IntegerField(default=60, help_text='Delay between retry attempts in seconds')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this model is available for new tasks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='ai_analysis_key_43fe09_idx'), models.Index(fields=['model_type', 'is_active'], name='ai_analysis_model_t_b9e39d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(default=dict, help_text='Model-specific parameters for this analysis')),
                ('additional_inputs', models.JSONField(blank=True, default=list, help_text='Additional image IDs for multi-image tasks (future use)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('DISPATCHED', 'Dispatched'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking async execution', max_length=255, null=True)),
                ('service_job_id', models.CharField(blank=True, help_text='Job ID returned by AI service', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When the task was sent to AI service', null=True)),
                ('started_processing_at', models.DateTimeField(blank=True, help_text='When AI service started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task finished (success or failure)', null=True)),
                ('result_file_path', models.CharField(blank=True, help_text="Relative path to result file (e.g., 'ai_results/2024/12/25/uuid.nii.gz')", max_length=500)),
                ('result_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata from AI service (processing time, model version, etc.)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('webhook_secret', models.CharField(default=ai_analysis.models.generate_webhook_secret, help_text='Secret token for webhook authentication', max_length=64)),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to=settings.AUTH_USER_MODEL)),
                ('input_image', models.ForeignKey(help_text='Primary input image for analysis', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='dicom_images.medicalimage')),
                ('model', models.ForeignKey(help_text='AI model used for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ai_analysis.aimodel')),
            ],
            options={
                'verbose_name': 'Analysis Task',
                'verbose_name_plural': 'Analysis Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='ai_analysis_created_af6d20_idx'), models.Index(fields=['status', '-created_at'], name='ai_analysis_status_66747a_idx'), models.Index(fields=['model', 'status'], name='ai_analysis_model_i_f1a8ab_idx')],
            },
        ),
    ]
