# Generated by Django 5.1.4 on 2025-12-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='anatomical_regions',
            field=models.JSONField(blank=True, default=list, help_text="Anatomical regions (e.g., ['brain', 'chest', 'abdomen'])"),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='authors',
            field=models.JSONField(blank=True, default=list, help_text="List of authors/contributors (e.g., [{'name': 'John Doe', 'affiliation': 'Institution', 'email': 'john@example.com'}])"),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='citation',
            field=models.TextField(blank=True, help_text='Formatted citation text'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Link to online demo or interactive notebook'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Link to full documentation'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='download_count',
            field=models.IntegerField(default=0, help_text='Number of times model has been used'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='example_images',
            field=models.JSONField(blank=True, default=list, help_text='URLs to example input/output images'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='homepage_url',
            field=models.URLField(blank=True, help_text='Project homepage'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='license_name',
            field=models.CharField(blank=True, help_text="License name (e.g., 'MIT', 'Apache 2.0', 'GPL-3.0')", max_length=100),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='license_url',
            field=models.URLField(blank=True, help_text='URL to full license text'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='limitations',
            field=models.TextField(blank=True, help_text='Known limitations or contraindications'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='medical_domains',
            field=models.JSONField(blank=True, default=list, help_text="Medical domains (e.g., ['neurology', 'radiology', 'oncology'])"),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='model_card_url',
            field=models.URLField(blank=True, help_text='Link to detailed model card documentation'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization or institution that developed the model', max_length=200),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='paper_url',
            field=models.URLField(blank=True, help_text='Link to paper (ArXiv, bioRxiv, etc.)'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict, help_text="Performance metrics (e.g., {'dice': 0.92, 'accuracy': 0.95, 'auc': 0.88})"),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='publication_doi',
            field=models.CharField(blank=True, help_text="DOI of the publication (e.g., '10.1000/xyz123')", max_length=100),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='publication_journal',
            field=models.CharField(blank=True, help_text='Journal or conference name', max_length=200),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='publication_title',
            field=models.CharField(blank=True, help_text='Title of the primary publication', max_length=500),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='publication_url',
            field=models.URLField(blank=True, help_text='URL to the publication (e.g., PubMed, ArXiv)'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='publication_year',
            field=models.IntegerField(blank=True, help_text='Year of publication', null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User rating (0.00-5.00)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='support_url',
            field=models.URLField(blank=True, help_text='Link to support forum or issue tracker'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Searchable tags (e.g., ['brain', 'mri', 'deep-learning', 'pytorch'])"),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='training_dataset',
            field=models.CharField(blank=True, help_text='Dataset used for training', max_length=200),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='use_cases',
            field=models.JSONField(blank=True, default=list, help_text='Example use cases or clinical applications'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='validation_dataset',
            field=models.CharField(blank=True, help_text='Dataset used for validation', max_length=200),
        ),
    ]
