# Generated by Django 5.1.4 on 2025-12-26 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_aimodel_anatomical_regions_aimodel_authors_and_more'),
        ('dicom_images', '0002_medicalimage_dicom_tags_medicalimage_max_pixel_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['created_by', 'status', '-created_at'], name='ai_analysis_created_defa2b_idx'),
        ),
    ]
