# Generated by Django 5.1.4 on 2025-12-27 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_add_task_composite_index'),
        ('dicom_images', '0002_medicalimage_dicom_tags_medicalimage_max_pixel_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['created_at', 'model', 'status'], name='ai_analysis_created_6e5a46_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['model', 'status', 'completed_at'], name='ai_analysis_model_i_96db23_idx'),
        ),
    ]
