# Generated by Django 5.1.4 on 2025-12-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_add_statistics_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='orchestrator_job_id',
            field=models.CharField(blank=True, help_text='Job ID returned by orchestrator service', max_length=255, null=True),
        ),
    ]
