# Generated by Django 5.1.4 on 2026-02-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0005_add_orchestrator_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='use_orchestrator',
            field=models.BooleanField(default=False, help_text='Route this model through the gRPC Orchestrator (True) or Celery REST dispatch (False)'),
        ),
    ]
