# Generated by Django 5.1.4 on 2026-03-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0007_aimodel_label_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='requires_anonymization',
            field=models.BooleanField(default=False, help_text="When True, analysis tasks can only be created if the input study has a completed anonymization job with profile 'full' or 'research'."),
        ),
    ]
