# Generated by Django 5.1.4 on 2026-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0008_aimodel_requires_anonymization'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Connector-specific key/value pairs. For NNUNetConnector: 'nnunet_dataset_id', 'nnunet_config', 'nnunet_folds'. For gRPC connectors: 'device', 'threads', etc."),
        ),
    ]
