# Generated by Django 5.1.4 on 2026-06-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0009_aimodel_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='supported_species',
            field=models.JSONField(blank=True, default=list, help_text="Veterinary species the model is validated for (e.g., ['canine', 'feline']). Empty = species-agnostic / unspecified."),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='anatomical_regions',
            field=models.JSONField(blank=True, default=list, help_text="Anatomical regions (e.g., ['thorax', 'abdomen', 'limb'])"),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='medical_domains',
            field=models.JSONField(blank=True, default=list, help_text="Clinical domains (e.g., ['cardiology', 'radiology', 'orthopedics'])"),
        ),
    ]
