# Generated by Django 5.1.4 on 2026-06-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0010_aimodel_supported_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], db_index=True, default='routine', help_text='Triage priority for the worklist (routine / urgent / STAT)', max_length=10),
        ),
    ]
