# Generated by Django 5.2.9 on 2025-12-20 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(db_index=True, help_text='Unique identifier for the study (StudyInstanceUID)', max_length=255, unique=True)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_birth_date', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('study_date', models.DateField(blank=True, db_index=True, null=True)),
                ('study_time', models.TimeField(blank=True, null=True)),
                ('study_description', models.TextField(blank=True)),
                ('accession_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Study',
                'verbose_name_plural': 'Medical Studies',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(db_index=True, help_text='Unique identifier for the series (SeriesInstanceUID)', max_length=255, unique=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('series_description', models.TextField(blank=True)),
                ('modality', models.CharField(db_index=True, help_text='Imaging modality (CT, MR, CR, DX, etc.)', max_length=10)),
                ('body_part_examined', models.CharField(blank=True, max_length=100)),
                ('protocol_name', models.CharField(blank=True, max_length=255)),
                ('series_date', models.DateField(blank=True, null=True)),
                ('series_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='dicom_images.medicalstudy')),
            ],
            options={
                'verbose_name': 'Medical Series',
                'verbose_name_plural': 'Medical Series',
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('quota_bytes', models.BigIntegerField(default=5368709120)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Storage Quota',
                'verbose_name_plural': 'User Storage Quotas',
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(db_index=True, help_text='Unique identifier for the instance (SOPInstanceUID)', max_length=255, unique=True)),
                ('sop_class_uid', models.CharField(help_text='SOP Class UID defining the image type', max_length=255)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(help_text='DICOM file', upload_to='dicom/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dcm', 'dicom'])])),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('original_filename', models.CharField(max_length=255)),
                ('rows', models.IntegerField(blank=True, help_text='Image height', null=True)),
                ('columns', models.IntegerField(blank=True, help_text='Image width', null=True)),
                ('number_of_frames', models.IntegerField(default=1, help_text='Number of frames in multi-frame image')),
                ('acquisition_datetime', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dicom_images.medicalseries')),
            ],
            options={
                'verbose_name': 'Medical Image',
                'verbose_name_plural': 'Medical Images',
                'ordering': ['instance_number'],
                'indexes': [models.Index(fields=['series', 'instance_number'], name='dicom_image_series__50dc4d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalstudy',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='dicom_image_uploade_0c8127_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstudy',
            index=models.Index(fields=['patient_id', 'study_date'], name='dicom_image_patient_fb7b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalseries',
            index=models.Index(fields=['study', 'series_number'], name='dicom_image_study_i_6a3d06_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalseries',
            index=models.Index(fields=['modality'], name='dicom_image_modalit_180776_idx'),
        ),
    ]
