# Generated by Django 4.1 on 2025-12-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicom_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='dicom_tags',
            field=models.JSONField(blank=True, default=dict, help_text='Complete DICOM tag dump'),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='max_pixel_value',
            field=models.IntegerField(blank=True, help_text='Maximum pixel value in image', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='min_pixel_value',
            field=models.IntegerField(blank=True, help_text='Minimum pixel value in image', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='pixel_spacing_column',
            field=models.FloatField(blank=True, help_text='Pixel spacing in column direction (mm)', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='pixel_spacing_row',
            field=models.FloatField(blank=True, help_text='Pixel spacing in row direction (mm)', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='slice_location',
            field=models.FloatField(blank=True, db_index=True, help_text='Slice location for 3D reconstruction', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='slice_thickness',
            field=models.FloatField(blank=True, help_text='Slice thickness (mm)', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='window_center',
            field=models.FloatField(blank=True, help_text='Default window center for display', null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='window_width',
            field=models.FloatField(blank=True, help_text='Default window width for display', null=True),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='dicom_tags',
            field=models.JSONField(blank=True, default=dict, help_text='Complete DICOM tag dump'),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='series_description_normalized',
            field=models.TextField(blank=True, db_index=True, help_text='Normalized description for search'),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='thumbnail_generated_at',
            field=models.DateTimeField(blank=True, help_text='When thumbnails were generated', null=True),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='thumbnail_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of thumbnail generation', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='thumbnail_large',
            field=models.ImageField(blank=True, help_text='512x512 thumbnail', null=True, upload_to='thumbnails/series/%Y/%m/%d/large/'),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, help_text='300x300 thumbnail', null=True, upload_to='thumbnails/series/%Y/%m/%d/medium/'),
        ),
        migrations.AddField(
            model_name='medicalseries',
            name='thumbnail_small',
            field=models.ImageField(blank=True, help_text='150x150 thumbnail', null=True, upload_to='thumbnails/series/%Y/%m/%d/small/'),
        ),
        migrations.AddField(
            model_name='medicalstudy',
            name='dicom_tags',
            field=models.JSONField(blank=True, default=dict, help_text='Complete DICOM tag dump for extensibility'),
        ),
        migrations.AddField(
            model_name='medicalstudy',
            name='patient_name_normalized',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized patient name for search', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalstudy',
            name='study_description_normalized',
            field=models.TextField(blank=True, db_index=True, help_text='Normalized description for full-text search'),
        ),
        migrations.AddField(
            model_name='userstoragequota',
            name='thumbnail_size_bytes',
            field=models.BigIntegerField(default=0, help_text='Storage used by thumbnails'),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('search_filters', models.JSONField(help_text='JSON object containing search parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('text', 'Text Label'), ('arrow', 'Arrow'), ('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('polygon', 'Polygon'), ('line', 'Line'), ('angle', 'Angle Measurement'), ('distance', 'Distance Measurement'), ('area', 'Area Measurement'), ('roi', 'Region of Interest')], max_length=20)),
                ('frame_number', models.IntegerField(default=0, help_text='Frame number for multi-frame images')),
                ('geometry_data', models.JSONField(help_text='Coordinates and properties in JSON format')),
                ('measurement_value', models.FloatField(blank=True, help_text='Calculated measurement value', null=True)),
                ('measurement_unit', models.CharField(blank=True, help_text='Unit of measurement (mm, mm², degrees, etc.)', max_length=20)),
                ('label', models.CharField(blank=True, help_text='User-defined label or title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description or clinical notes')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dicom_images.medicalimage')),
            ],
            options={
                'verbose_name': 'Image Annotation',
                'verbose_name_plural': 'Image Annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Lung Nodule ROI')", max_length=255)),
                ('annotation_type', models.CharField(help_text='Type of annotation this template creates', max_length=20)),
                ('default_properties', models.JSONField(help_text='Default geometry and style properties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annotation Template',
                'verbose_name_plural': 'Annotation Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', '-last_used_at'], name='dicom_image_user_id_f6d94c_idx'),
        ),
        migrations.AddIndex(
            model_name='imageannotation',
            index=models.Index(fields=['image', 'frame_number'], name='dicom_image_image_i_21b7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='imageannotation',
            index=models.Index(fields=['created_by', '-created_at'], name='dicom_image_created_704449_idx'),
        ),
        migrations.AddIndex(
            model_name='imageannotation',
            index=models.Index(fields=['annotation_type'], name='dicom_image_annotat_bba2fa_idx'),
        ),
    ]
