# Generated by Django 5.1.4 on 2026-01-10 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0002_medicalimage_dicom_tags_medicalimage_max_pixel_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='sop_instance_uid',
            field=models.CharField(db_index=True, help_text='Unique identifier for the instance (SOPInstanceUID) - scoped per series', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalseries',
            name='series_instance_uid',
            field=models.CharField(db_index=True, help_text='Unique identifier for the series (SeriesInstanceUID) - scoped per study', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalstudy',
            name='study_instance_uid',
            field=models.CharField(db_index=True, help_text='Unique identifier for the study (StudyInstanceUID) - scoped per user', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='medicalimage',
            constraint=models.UniqueConstraint(fields=('sop_instance_uid', 'series'), name='unique_instance_per_series'),
        ),
        migrations.AddConstraint(
            model_name='medicalseries',
            constraint=models.UniqueConstraint(fields=('series_instance_uid', 'study'), name='unique_series_per_study'),
        ),
        migrations.AddConstraint(
            model_name='medicalstudy',
            constraint=models.UniqueConstraint(fields=('study_instance_uid', 'uploaded_by'), name='unique_study_per_user'),
        ),
    ]
