# Generated by Django 5.1.4 on 2026-01-10 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0003_user_scoped_duplicates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicalimage',
            name='unique_instance_per_series',
        ),
        migrations.RemoveConstraint(
            model_name='medicalseries',
            name='unique_series_per_study',
        ),
        migrations.RemoveConstraint(
            model_name='medicalstudy',
            name='unique_study_per_user',
        ),
        migrations.AddIndex(
            model_name='medicalimage',
            index=models.Index(fields=['sop_instance_uid', 'series', '-uploaded_at'], name='dicom_image_sop_ins_e9aa13_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalseries',
            index=models.Index(fields=['series_instance_uid', 'study', '-created_at'], name='dicom_image_series__62ee7f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstudy',
            index=models.Index(fields=['study_instance_uid', 'uploaded_by', '-uploaded_at'], name='dicom_image_study_i_ab1aac_idx'),
        ),
    ]
