# Generated by Django 5.1.4 on 2026-02-15 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0004_allow_duplicate_uploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_ids', models.JSONField(blank=True, default=list, help_text='List of MedicalImage IDs to anonymize (used when no study is specified)')),
                ('profile', models.CharField(choices=[('basic', 'Basic'), ('full', 'Full'), ('research', 'Research')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('result_file_path', models.CharField(blank=True, help_text='Relative path to the output ZIP file', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_jobs', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymization_jobs', to='dicom_images.medicalstudy')),
            ],
            options={
                'verbose_name': 'Anonymization Job',
                'verbose_name_plural': 'Anonymization Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='dicom_image_created_91a02f_idx'), models.Index(fields=['status'], name='dicom_image_status_bb0f7c_idx')],
            },
        ),
    ]
