# Generated by Django 5.1.4 on 2026-02-15 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0005_anonymizationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('export', 'Export'), ('delete', 'Delete'), ('analyze', 'Analyze')], max_length=20)),
                ('study_ids', models.JSONField(default=list, help_text='List of MedicalStudy IDs to process')),
                ('model_key', models.CharField(blank=True, help_text='AI model key (for analyze operation)', max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters for the operation')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('result_file_path', models.CharField(blank=True, help_text='Relative path to the output file (for export)', max_length=500)),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Summary of the operation result')),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Job',
                'verbose_name_plural': 'Batch Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='dicom_image_created_6f2220_idx'), models.Index(fields=['status'], name='dicom_image_status_ae8d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_ids', models.JSONField(blank=True, default=list, help_text='List of MedicalSeries IDs (for NIfTI conversion)')),
                ('target_format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('nifti', 'NIfTI')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('result_file_path', models.CharField(blank=True, help_text='Relative path to the output file or ZIP', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to='dicom_images.medicalstudy')),
            ],
            options={
                'verbose_name': 'Conversion Job',
                'verbose_name_plural': 'Conversion Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='dicom_image_created_e623d6_idx'), models.Index(fields=['status'], name='dicom_image_status_0fba2e_idx')],
            },
        ),
    ]
