# Generated by Django 5.1.4 on 2026-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0006_batchjob_conversionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizationjob',
            name='output_format',
            field=models.CharField(choices=[('dicom_zip', 'DICOM ZIP'), ('nifti_bids', 'NIfTI + BIDS JSON'), ('png_bids', 'PNG + BIDS JSON')], default='dicom_zip', max_length=20),
        ),
    ]
