"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS configuration from environment
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'daphne',  # MUST be first for ASGI support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',  # OpenAPI 3 schema generation
    'corsheaders',
    'django_filters',
    'channels',  # WebSocket support for real-time Monitor page
    'users',
    'files',
    'dicom_images',
    'core',
    'ai_analysis',  # AI Analysis Orchestrator
    'dicom_gateway',  # DICOM Gateway Management
    'credentials',  # Enhanced Authentication & Session Tracking
    'reports',  # Structured Reports & PDF Export
    'patients',  # Veterinary patient registry (Owner → AnimalPatient)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'credentials.middleware.RequestContextMiddleware',  # Store request context for signal handlers
    'credentials.middleware.AuditLoggingMiddleware',  # Audit logging and brute force protection
]

# CORS Configuration - Environment-based
CORS_ALLOW_ALL_ORIGINS = False  # Never allow all in production
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'
).split(',')
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True') == 'True'


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ASGI Application (for WebSocket support with Django Channels)
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'db-vetimage'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path.joinpath(BASE_DIR, 'staticfiles')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path.joinpath(BASE_DIR, 'media')

# Medical Image Storage Settings
DICOM_STORAGE_PATH = Path.joinpath(MEDIA_ROOT, 'dicom')
MAX_UPLOAD_SIZE = 100 * 1024 * 1024  # 100 MB per file
USER_STORAGE_QUOTA = 5 * 1024 * 1024 * 1024  # 5 GB per user

# Multi-format support for medical images
ALLOWED_DICOM_EXTENSIONS = ['.dcm', '.dicom']  # Backward compatibility
ALLOWED_MEDICAL_IMAGE_EXTENSIONS = [
    # DICOM formats
    '.dcm', '.dicom',
    # NIfTI formats
    '.nii', '.nii.gz',
    # Standard image formats
    '.jpg', '.jpeg', '.png',
]

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
DATA_UPLOAD_MAX_NUMBER_FILES = 10000  # DICOM series can have hundreds of slices

# DICOM Image Rendering Settings (WADO-RS)
IMAGE_RENDER_FORMAT = 'JPEG'  # Default output format ('JPEG' or 'PNG')
IMAGE_RENDER_QUALITY = 90  # JPEG quality (1-100)
IMAGE_MAX_DIMENSION = 2048  # Maximum width/height for rendered images
ENABLE_IMAGE_CACHE = True  # Enable caching of rendered frames
IMAGE_CACHE_TIMEOUT = 3600  # Cache timeout in seconds (1 hour)

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Keep for Django admin
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'users.exceptions.custom_exception_handler',

    # Pagination — all list endpoints paginate by default
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,

    # API Schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Rate limiting — protects unauthenticated auth endpoints (brute force /
    # credential stuffing) and provides a default ceiling for the rest.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_LOGIN', '10/min'),
        'register': os.getenv('THROTTLE_REGISTER', '5/min'),
        'password_reset': os.getenv('THROTTLE_PASSWORD_RESET', '5/min'),
        'token_refresh': os.getenv('THROTTLE_TOKEN_REFRESH', '30/min'),
    },
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'VetImage Veterinary Imaging Platform API',
    'DESCRIPTION': '''
    RESTful API for veterinary DICOM imaging: owner/patient registry, DICOM
    storage with DICOMweb support, AI-assisted analysis, measurements (VHS),
    structured reporting with veterinarian sign-off, and owner result sharing.

    **Features:**
    - JWT authentication
    - Owner → Animal Patient → Study registry
    - DICOM upload & storage; DICOMweb QIDO-RS / WADO-RS
    - Species-aware AI model catalog & analysis tasks (with triage priority)
    - Vertebral Heart Score (VHS) measurements with trend tracking
    - Structured veterinary reports, PDF export, vet sign-off, owner share links
    - Image annotations with automatic measurements; anonymization & conversion

    **Authentication:**
    Most endpoints require authentication. Obtain a JWT access token from
    `/users/auth/login/`, then click **Authorize** and paste the token, or send
    `Authorization: Bearer <token>` manually.

    **Responsible use:** AI output is veterinary decision support — not a
    diagnosis. Results require review and sign-off by a qualified veterinarian.
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Security: declare the bearer (JWT) scheme AND make the Authorize button
    # work by defining the referenced securityScheme component.
    'SECURITY': [{'bearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT access token from /users/auth/login/',
            },
        },
    },
    'COMPONENT_SPLIT_REQUEST': True,

    # Logical grouping of operations in the docs UI.
    'TAGS': [
        {'name': 'Auth', 'description': 'Authentication & user profile'},
        {'name': 'Patients', 'description': 'Owners, animal patients & signalment'},
        {'name': 'VHS', 'description': 'Vertebral Heart Score measurements'},
        {'name': 'DICOM', 'description': 'DICOM upload, storage & DICOMweb'},
        {'name': 'AI Analysis', 'description': 'AI models & analysis tasks'},
        {'name': 'Reports', 'description': 'Structured reports, sign-off & sharing'},
        {'name': 'Credentials', 'description': 'API keys, sessions & audit'},
        {'name': 'Gateway', 'description': 'DICOM gateway & transfers'},
    ],

    # Contact and license info
    'CONTACT': {
        'name': 'VetImage Support',
        'email': 'support@vetimage.app',
    },
    'LICENSE': {
        'name': 'Proprietary',
    },

    # Schema endpoint behavior
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_AUTHENTICATION': None,

    # Swagger UI settings
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'filter': True,
        'tryItOutEnabled': True,
    },

    # Component naming
    'SCHEMA_PATH_PREFIX': '/api/',
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 5))),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 10080))),
    'ROTATE_REFRESH_TOKENS': True,  # Generate new refresh token on refresh
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh token
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

# Cookie Settings for Refresh Token
REFRESH_TOKEN_COOKIE_NAME = 'refresh_token'
# Don't set domain - allows cookie to work for both localhost and 127.0.0.1
REFRESH_TOKEN_COOKIE_DOMAIN = os.getenv('COOKIE_DOMAIN', None)
REFRESH_TOKEN_COOKIE_SECURE = os.getenv('COOKIE_SECURE', 'False') == 'True'
REFRESH_TOKEN_COOKIE_HTTPONLY = os.getenv('COOKIE_HTTPONLY', 'True') == 'True'
REFRESH_TOKEN_COOKIE_SAMESITE = os.getenv('COOKIE_SAMESITE', 'Lax')
REFRESH_TOKEN_COOKIE_MAX_AGE = int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 10080)) * 60  # Convert minutes to seconds

# ---------------------------------------------------------------------------
# Production security hardening
# ---------------------------------------------------------------------------
# When DEBUG is off (production), enforce HTTPS-only cookies, SSL redirect, HSTS,
# and standard browser protections. These can still be tuned via env vars.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The refresh-token cookie must be Secure in production regardless of env.
    REFRESH_TOKEN_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 31536000))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True

# GDPR owner-PII retention window (days). 0 = disabled. The purge_expired_pii
# management command anonymizes owners not updated within this window.
OWNER_PII_RETENTION_DAYS = int(os.getenv('OWNER_PII_RETENTION_DAYS', 0) or 0)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@vetimage.local')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# ============================================================================
# Celery Configuration (Medical AI Analysis Orchestrator)
# ============================================================================

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis-vetimage:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis-vetimage:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Use Django's timezone setting
CELERY_TASK_TIME_LIMIT = 3600  # 1 hour hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 3300  # 55 minutes soft limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time for long-running jobs
CELERY_TASK_ACKS_LATE = True  # Acknowledge after task completes (more reliable)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # Prevent memory leaks by recycling workers

# Task Queues - Route different task types to different queues
CELERY_TASK_ROUTES = {
    'ai_analysis.tasks.dispatch_ai_job': {'queue': 'ai_jobs'},
    'ai_analysis.tasks.check_task_timeouts': {'queue': 'monitoring'},
    'ai_analysis.tasks.cleanup_old_tasks': {'queue': 'monitoring'},
    'ai_analysis.tasks.sync_orchestrator_status': {'queue': 'monitoring'},
    'patients.tasks.send_vaccination_reminders': {'queue': 'monitoring'},
}

# ============================================================================
# Django Cache Configuration (Redis for session tracking and rate limiting)
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://redis-vetimage:6379/1'),  # Use DB 1 for cache
        'KEY_PREFIX': 'vetimage',
        'TIMEOUT': 300,  # Default timeout: 5 minutes
    }
}

# ============================================================================
# Django Channels Configuration (WebSocket Support for Real-time Monitor)
# ============================================================================

# Channel layers - uses same Redis instance as Celery
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.getenv('REDIS_HOST', 'redis-vetimage'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

# ============================================================================
# AI Analysis Settings (MAIO - Medical AI Analysis Orchestrator)
# ============================================================================

# Backend base URL for webhook callbacks
BACKEND_BASE_URL = os.getenv('BACKEND_BASE_URL', 'http://backend-vetimage:3080')

# AI Results Storage
AI_RESULTS_PATH = Path.joinpath(MEDIA_ROOT, 'ai_results')

# Task Configuration
AI_TASK_DEFAULT_TIMEOUT = int(os.getenv('AI_TASK_DEFAULT_TIMEOUT', 1800))  # 30 minutes
AI_TASK_CLEANUP_DAYS = int(os.getenv('AI_TASK_CLEANUP_DAYS', 30))  # Delete old tasks after 30 days

# ============================================================================
# Orchestrator Configuration
# ============================================================================

ORCHESTRATOR_HOST = os.getenv('ORCHESTRATOR_HOST', 'orchestrator-vetimage')
ORCHESTRATOR_PORT = int(os.getenv('ORCHESTRATOR_PORT', 50050))
USE_ORCHESTRATOR = os.getenv('USE_ORCHESTRATOR', 'False') == 'True'
ORCHESTRATOR_POLL_INTERVAL = int(os.getenv('ORCHESTRATOR_POLL_INTERVAL', 5))

# ============================================================================
# Real-Time Update Configuration
# ============================================================================

# Use WebSocket for real-time updates (default: False for reliability)
# Set to True to enable WebSocket-based updates instead of polling
WEBSOCKET_BASED_TRACKING = os.getenv('WEBSOCKET_BASED_TRACKING', 'False') == 'True'

# Polling intervals when WebSocket is disabled (in seconds)
MONITOR_POLL_INTERVAL = int(os.getenv('MONITOR_POLL_INTERVAL', 30))  # Task/transfer lists
STATS_POLL_INTERVAL = int(os.getenv('STATS_POLL_INTERVAL', 30))      # Statistics

# WebSocket heartbeat interval when enabled (in seconds)
WEBSOCKET_HEARTBEAT_INTERVAL = int(os.getenv('WEBSOCKET_HEARTBEAT_INTERVAL', 30))

# ============================================================================
# PACS User Mapping Configuration
# ============================================================================

# DEPRECATED: Password-based PACS authentication (removed in favor of API keys)
#
# Previously used PACS_SERVICE_CREDENTIALS for password-based authentication.
# Now replaced with UserAPIKey model for secure API key-based authentication.
#
# New Authentication Flow:
# 1. Admin generates API key via Django admin (/admin/users/userapikey/)
# 2. API key is configured in gateway PACS_USER_API_KEYS environment variable
# 3. Gateway authenticates using /users/auth/api-key/ endpoint
# 4. API keys are hashed with SHA-256 and never stored in plaintext
#
# For backward compatibility, gateway service account still uses password-based
# authentication via /users/auth/login/ endpoint.

# ============================================================================
# Credentials App Configuration
# ============================================================================

# Session tracking
MAX_CONCURRENT_SESSIONS_PER_USER = int(os.getenv('MAX_CONCURRENT_SESSIONS_PER_USER', 5))
SESSION_ACTIVITY_TIMEOUT_MINUTES = int(os.getenv('SESSION_ACTIVITY_TIMEOUT_MINUTES', 30))

# Brute force protection
MAX_LOGIN_ATTEMPTS = int(os.getenv('MAX_LOGIN_ATTEMPTS', 5))
LOGIN_ATTEMPT_TIMEOUT_SECONDS = int(os.getenv('LOGIN_ATTEMPT_TIMEOUT_SECONDS', 900))  # 15 min

# API key rate limiting (defaults)
DEFAULT_API_KEY_RATE_LIMIT_PER_MINUTE = int(os.getenv('DEFAULT_API_KEY_RATE_LIMIT_PER_MINUTE', 60))
DEFAULT_API_KEY_RATE_LIMIT_PER_HOUR = int(os.getenv('DEFAULT_API_KEY_RATE_LIMIT_PER_HOUR', 3600))
DEFAULT_API_KEY_RATE_LIMIT_PER_DAY = int(os.getenv('DEFAULT_API_KEY_RATE_LIMIT_PER_DAY', 86400))

# Feature flags
CREDENTIALS_TRACKING_ENABLED = os.getenv('CREDENTIALS_TRACKING_ENABLED', 'True') == 'True'
CREDENTIALS_AUDIT_LOGGING_ENABLED = os.getenv('CREDENTIALS_AUDIT_LOGGING_ENABLED', 'True') == 'True'
CREDENTIALS_RATE_LIMITING_ENABLED = os.getenv('CREDENTIALS_RATE_LIMITING_ENABLED', 'False') == 'True'

# GeoIP (optional)
GEOIP_DATABASE_PATH = os.getenv('GEOIP_DATABASE_PATH', '/app/geoip/GeoLite2-City.mmdb')

# Audit log retention (days)
AUDIT_LOG_RETENTION_DAYS = int(os.getenv('AUDIT_LOG_RETENTION_DAYS', 365))

# ============================================================================
# DICOM Anonymization Settings
# ============================================================================

ANONYMIZATION_OUTPUT_PATH = Path.joinpath(MEDIA_ROOT, 'anonymized')
ANONYMIZATION_MAX_IMAGES = int(os.getenv('ANONYMIZATION_MAX_IMAGES', 500))

# ============================================================================
# Orthanc PACS Settings (used for DICOM SEG upload)
# ============================================================================

ORTHANC_URL = os.getenv('ORTHANC_URL', 'http://orthanc-test-pacs:8042')
ORTHANC_USERNAME = os.getenv('ORTHANC_USERNAME', 'orthanc')
ORTHANC_PASSWORD = os.getenv('ORTHANC_PASSWORD', 'orthanc')


# ============================================================================
# nnU-Net Settings (used by NNUNetConnector / run_nnunet_inference task)
# ============================================================================

# Path to nnU-Net model weights directory (maps to nnUNet_results env var).
# Set to None if weights are provided directly via the OS environment.
NNUNET_RESULTS = os.getenv('NNUNET_RESULTS', None)
