"""
Report Builder Service

Builds structured JSON report content from AI analysis task results.
"""

from django.utils import timezone


class ReportBuilder:
    """Builds structured report content from an AnalysisTask."""

    def build_from_task(self, task):
        """
        Build a structured JSON report from a completed AnalysisTask.

        Returns a dict with the full report content schema:
        {
            report_type, generated_at, model_info, patient_info,
            sections[], summary, disclaimer
        }
        """
        study = task.input_image.series.study
        model = task.model

        return {
            'report_type': 'AI Analysis Report',
            'generated_at': timezone.now().isoformat(),
            'model_info': self._build_model_info(model),
            'patient_info': self._build_patient_info(study),
            'sections': self._build_sections(task),
            'summary': self._build_summary(task),
            'disclaimer': (
                'This report was generated by an AI model and is intended '
                'for research purposes only. It should not be used as a '
                'substitute for professional medical diagnosis. All findings '
                'must be reviewed and validated by a qualified healthcare '
                'professional before any clinical decisions are made.'
            ),
        }

    def _build_model_info(self, model):
        """Extract model information."""
        if not model:
            return {'name': 'Unknown', 'version': 'N/A', 'type': 'N/A'}

        return {
            'name': model.name,
            'key': model.key,
            'version': model.version,
            'type': model.get_model_type_display(),
        }

    def _build_patient_info(self, study):
        """Extract patient info from the study."""
        return {
            'patient_id': study.patient_id or 'N/A',
            'patient_name': study.patient_name or 'N/A',
            'study_date': str(study.study_date) if study.study_date else 'N/A',
            'study_description': study.study_description or 'N/A',
            'study_uid': study.study_instance_uid,
        }

    def _build_sections(self, task):
        """
        Extract sections from task result_metadata.

        Handles varying metadata structures by extracting known
        keys into standardised section objects.
        """
        metadata = task.result_metadata or {}
        sections = []

        # Findings section
        findings = metadata.get('findings', metadata.get('results', []))
        if findings:
            sections.append({
                'title': 'Findings',
                'type': 'findings',
                'items': findings if isinstance(findings, list) else [findings],
            })

        # Measurements section
        measurements = metadata.get('measurements', {})
        if measurements:
            sections.append({
                'title': 'Measurements',
                'type': 'measurements',
                'data': measurements,
            })

        # Confidence / scores section
        confidence = metadata.get('confidence', metadata.get('scores', {}))
        if confidence:
            sections.append({
                'title': 'Confidence Scores',
                'type': 'scores',
                'data': confidence,
            })

        # Technical details section
        technical = {}
        for key in ('processing_time', 'model_version', 'input_shape', 'parameters'):
            if key in metadata:
                technical[key] = metadata[key]
        if technical:
            sections.append({
                'title': 'Technical Details',
                'type': 'technical',
                'data': technical,
            })

        # If nothing was extracted, add a raw metadata section
        if not sections and metadata:
            sections.append({
                'title': 'Analysis Results',
                'type': 'raw',
                'data': metadata,
            })

        return sections

    def _build_summary(self, task):
        """Build a summary string from task metadata."""
        metadata = task.result_metadata or {}
        model_name = task.model.name if task.model else 'AI model'

        summary_parts = [f'Analysis performed by {model_name}.']

        if task.processing_duration:
            summary_parts.append(
                f'Processing completed in {task.processing_duration:.1f} seconds.'
            )

        findings = metadata.get('findings', metadata.get('results', []))
        if isinstance(findings, list) and findings:
            summary_parts.append(f'{len(findings)} finding(s) reported.')

        return ' '.join(summary_parts)
