# Generated by Django 5.1.4 on 2026-02-15 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_analysis', '0005_add_orchestrator_job_id'),
        ('dicom_images', '0005_anonymizationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict, help_text='Structured report content (sections, findings, scores)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_task', models.ForeignKey(help_text='Source analysis task', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ai_analysis.analysistask')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(help_text='Associated medical study', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dicom_images.medicalstudy')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='reports_rep_created_9a90fa_idx'), models.Index(fields=['analysis_task'], name='reports_rep_analysi_01bd0e_idx')],
            },
        ),
    ]
