# Generated by Django 5.1.4 on 2026-02-15 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('radiology', 'Radiology'), ('pathology', 'Pathology'), ('general', 'General'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('layout', models.JSONField(default=dict, help_text='Template layout with sections, disclaimer, header_fields')),
                ('is_default', models.BooleanField(default=False, help_text='System-provided default templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate'),
        ),
    ]
