# Generated by Django 5.1.4 on 2026-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_approved_at_report_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
