# Generated by Django 5.1.4 on 2026-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_share_token_report_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='modality_filter',
            field=models.JSONField(blank=True, default=list, help_text="DICOM modality codes this template applies to. Example: ['CR', 'DX', 'US']"),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='species_filter',
            field=models.JSONField(blank=True, default=list, help_text="Empty list = all species. Example: ['canine', 'feline']"),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_type',
            field=models.CharField(choices=[('radiology', 'Radiology'), ('pathology', 'Pathology'), ('general', 'General'), ('custom', 'Custom'), ('thoracic_canine', 'Thoracic Radiograph — Canine'), ('thoracic_feline', 'Thoracic Radiograph — Feline'), ('thoracic_equine', 'Thoracic Radiograph — Equine'), ('abdominal_us', 'Abdominal Ultrasound'), ('orthopedic', 'Orthopedic Assessment'), ('dental', 'Dental Radiograph'), ('cardiac_vhs', 'Cardiac / VHS Report'), ('discharge_summary', 'Discharge Summary'), ('vaccination_certificate', 'Vaccination Certificate'), ('referral_letter', 'Specialist Referral'), ('soap_note', 'SOAP Clinical Note')], default='custom', max_length=30),
        ),
    ]
