# Generated by Django 5.1.4 on 2026-06-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='users.organization')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('equine', 'Equine'), ('bovine', 'Bovine'), ('avian', 'Avian'), ('exotic', 'Exotic'), ('other', 'Other')], db_index=True, max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('MN', 'Male Neutered'), ('FS', 'Female Spayed'), ('U', 'Unknown')], max_length=2)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('microchip_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='patients.owner')),
            ],
            options={
                'verbose_name': 'Animal Patient',
                'verbose_name_plural': 'Animal Patients',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['organization', 'last_name'], name='patients_ow_organiz_0a9034_idx'),
        ),
        migrations.AddIndex(
            model_name='animalpatient',
            index=models.Index(fields=['owner', 'species'], name='patients_an_owner_i_6a7f25_idx'),
        ),
    ]
