# Generated by Django 5.1.4 on 2026-06-02 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VHSMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=200)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=200)),
                ('measured_on', models.DateField(help_text='Date of the radiograph the measurement was taken from')),
                ('long_axis_vertebrae', models.DecimalField(decimal_places=1, help_text='Long cardiac axis in vertebral units (e.g. 5.5)', max_digits=4)),
                ('short_axis_vertebrae', models.DecimalField(decimal_places=1, help_text='Short cardiac axis in vertebral units (e.g. 4.5)', max_digits=4)),
                ('vhs', models.DecimalField(decimal_places=1, help_text='Computed VHS = long + short (vertebral units)', max_digits=4)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('ai_assisted', 'AI-assisted (clinician-confirmed)')], default='manual', max_length=20)),
                ('landmark_points', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vhs_measurements', to='patients.animalpatient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vhs_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VHS Measurement',
                'verbose_name_plural': 'VHS Measurements',
                'ordering': ['-measured_on', '-created_at'],
                'indexes': [models.Index(fields=['animal_patient', '-measured_on'], name='patients_vh_animal__158ac8_idx')],
            },
        ),
    ]
