# Generated by Django 5.1.4 on 2026-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_vhsmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='pii_anonymized',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
