# Generated by Django 5.1.4 on 2026-06-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0008_medicalstudy_animal_patient'),
        ('patients', '0003_owner_pii_anonymized'),
        ('reports', '0005_reporttemplate_modality_filter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalpatient',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
        migrations.CreateModel(
            name='ClinicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('visit_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('vaccination', 'Vaccination'), ('surgery', 'Surgery'), ('imaging', 'Imaging'), ('emergency', 'Emergency')], db_index=True, default='consultation', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.animalpatient')),
                ('attending_vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('linked_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_visits', to='reports.report')),
                ('linked_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_visits', to='dicom_images.medicalstudy')),
            ],
            options={
                'verbose_name': 'Clinical Visit',
                'verbose_name_plural': 'Clinical Visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('vaccination', 'Vaccination'), ('surgery', 'Surgery'), ('imaging', 'Imaging'), ('emergency', 'Emergency')], default='consultation', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.animalpatient')),
                ('attending_vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('linked_visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='patients.clinicalvisit')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('administered_on', models.DateField()),
                ('next_due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccinations', to=settings.AUTH_USER_MODEL)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.animalpatient')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['-administered_on'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bcs', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], help_text='Body Condition Score 1–9 (Purina/WSAVA scale). 1=emaciated, 5=ideal, 9=obese.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='patients.animalpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
                'ordering': ['-measured_on'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalvisit',
            index=models.Index(fields=['animal_patient', '-visit_date'], name='patients_cl_animal__f375ec_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['animal_patient', 'scheduled_at'], name='patients_ap_animal__99e366_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['attending_vet', 'scheduled_at'], name='patients_ap_attendi_6463fa_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='patients_ap_status_d4defc_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['animal_patient', 'next_due_on'], name='patients_va_animal__afe3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['animal_patient', '-measured_on'], name='patients_we_animal__9a0cea_idx'),
        ),
    ]
