# Generated by Django 5.1.4 on 2026-06-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_animalpatient_profile_photo_clinicalvisit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=200)),
                ('allergen_type', models.CharField(choices=[('drug', 'Drug'), ('food', 'Food'), ('environmental', 'Environmental'), ('contact', 'Contact')], max_length=20)),
                ('reaction', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-threatening')], max_length=20)),
                ('first_observed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.animalpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allergy Record',
                'verbose_name_plural': 'Allergy Records',
                'ordering': ['-severity', 'allergen'],
                'indexes': [models.Index(fields=['animal_patient', 'severity'], name='patients_al_animal__ff3c72_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='patients/clinical/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('body_region', models.CharField(blank=True, max_length=100)),
                ('taken_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_photos', to='patients.animalpatient')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_photos', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='patients.clinicalvisit')),
            ],
            options={
                'verbose_name': 'Clinical Photo',
                'verbose_name_plural': 'Clinical Photos',
                'ordering': ['-taken_on', '-created_at'],
                'indexes': [models.Index(fields=['animal_patient', '-taken_on'], name='patients_cl_animal__d9ea59_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('urinalysis', 'Urinalysis'), ('cytology', 'Cytology'), ('serology', 'Serology'), ('microbiology', 'Microbiology'), ('other', 'Other')], db_index=True, max_length=20)),
                ('panel_name', models.CharField(max_length=200)),
                ('result_date', models.DateField(db_index=True)),
                ('result_data', models.JSONField(default=dict, help_text='Analyte map: {name: {value, unit, ref_low, ref_high, flag}}')),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='patients/labs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.animalpatient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='patients.clinicalvisit')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-result_date', '-created_at'],
                'indexes': [models.Index(fields=['animal_patient', '-result_date'], name='patients_la_animal__ecba00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_on', models.DateField()),
                ('medication_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, help_text="e.g. '5 mg/kg'", max_length=100)),
                ('route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('topical', 'Topical'), ('injection_sc', 'Subcutaneous injection'), ('injection_im', 'Intramuscular injection'), ('injection_iv', 'Intravenous injection'), ('inhalation', 'Inhalation'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic'), ('other', 'Other')], max_length=20)),
                ('frequency', models.CharField(blank=True, help_text="e.g. 'BID', 'SID', 'PRN'", max_length=100)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('refills_remaining', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.animalpatient')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='patients.clinicalvisit')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_on', '-created_at'],
                'indexes': [models.Index(fields=['animal_patient', '-prescribed_on'], name='patients_pr_animal__0e758d_idx')],
            },
        ),
    ]
