# Generated by Django 5.1.4 on 2026-06-10 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_allergyrecord_clinicalphoto_labresult_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalpatient',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animalpatient',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animalpatient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='BreedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('equine', 'Equine'), ('bovine', 'Bovine'), ('avian', 'Avian'), ('exotic', 'Exotic'), ('other', 'Other')], db_index=True, max_length=20)),
                ('breed_pattern', models.CharField(blank=True, help_text="Case-insensitive substring matched against the animal's breed. Blank = whole species.", max_length=100)),
                ('metric', models.CharField(db_index=True, default='vhs', max_length=50)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.CharField(blank=True, help_text='Citation for the reference range.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breed Reference Range',
                'verbose_name_plural': 'Breed Reference Ranges',
                'ordering': ['species', 'metric', 'breed_pattern'],
                'indexes': [models.Index(fields=['species', 'metric'], name='patients_br_species_71e1cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('species', 'breed_pattern', 'metric'), name='unique_breed_reference')],
            },
        ),
        migrations.CreateModel(
            name='ReproductiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('heat', 'Heat / Estrus'), ('mating', 'Mating'), ('pregnancy_confirmed', 'Pregnancy Confirmed'), ('whelping', 'Whelping / Queening / Foaling'), ('litter_registration', 'Litter Registration'), ('spay_neuter', 'Spay / Neuter'), ('other', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('partner_id', models.CharField(blank=True, help_text='Sire/dam identifier (microchip or registry no.)', max_length=100)),
                ('litter_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to='patients.animalpatient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproductive_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reproductive Event',
                'verbose_name_plural': 'Reproductive Events',
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['animal_patient', '-event_date'], name='patients_re_animal__c00478_idx')],
            },
        ),
    ]
