# Generated by Django 5.1.4 on 2026-06-14 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_images', '0009_studysharelink'),
        ('patients', '0006_animalpatient_insurance_expiry_and_more'),
        ('reports', '0005_reporttemplate_modality_filter_and_more'),
        ('users', '0012_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferringClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referring_clinics', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_clinics', to='users.organization')),
            ],
            options={
                'verbose_name': 'Referring Clinic',
                'verbose_name_plural': 'Referring Clinics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('history_summary', models.TextField(blank=True, help_text='Condensed patient history snapshot at referral time.')),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=10)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('recipient_email', models.EmailField(blank=True, help_text='For audit trail only; not used for access control.', max_length=254)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_packages', to='patients.animalpatient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referral_packages', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_packages', to='reports.report')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_packages', to='dicom_images.medicalstudy')),
                ('referring_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='patients.referringclinic')),
            ],
            options={
                'verbose_name': 'Referral Package',
                'verbose_name_plural': 'Referral Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='External clinic this case was referred from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='patients.referringclinic'),
        ),
        migrations.AddIndex(
            model_name='referringclinic',
            index=models.Index(fields=['organization', 'name'], name='patients_re_organiz_c5189e_idx'),
        ),
        migrations.AddIndex(
            model_name='referralpackage',
            index=models.Index(fields=['animal_patient', '-created_at'], name='patients_re_animal__fe8cfc_idx'),
        ),
    ]
