# Generated by Django 5.2.17 on 2026-09-01 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_rename_organization_to_clinic'),
        ('users', '0015_rename_users_clini_name_idx_users_clini_name_ec26e6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='users.clinic'),
        ),
        migrations.AlterField(
            model_name='referringclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_clinics', to='users.clinic'),
        ),
    ]
