# Generated by Django 5.1.4 on 2025-12-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organization_user_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Department or division (e.g., Radiology, Cardiology)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_sharing_jobs_with_colleagues',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow colleagues in same organization to view your analysis jobs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text='Job title or role (e.g., Radiologist, Technician)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Team or group name for project-based work', max_length=100),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'is_sharing_jobs_with_colleagues', 'department'], name='users_userp_organiz_7ecef8_idx'),
        ),
    ]
