# Generated by Django 5.1.4 on 2026-01-07 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_profile_org_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_sharing_jobs_with_colleagues',
            field=models.BooleanField(db_index=True, default=True, help_text='Allow colleagues in same organization to view your analysis jobs'),
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable identifier (e.g., "Orthanc PACS Key")', max_length=100)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the API key', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 characters of key for display purposes', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of last authentication with this key', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for key rotation', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive keys cannot be used for authentication')),
                ('user', models.ForeignKey(help_text='User that owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'user_api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='user_api_ke_key_has_bb7ba2_idx'), models.Index(fields=['user', 'is_active'], name='user_api_ke_user_id_ddad2e_idx')],
            },
        ),
    ]
