# Generated by Django 5.1.4 on 2026-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_language_field_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(1, 'Veterinarian'), (2, 'Guest'), (3, 'Clinic Admin'), (4, 'Veterinary Radiologist'), (5, 'Superuser')], default=1),
        ),
    ]
