# Generated by Django 5.1.4 on 2026-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(1, 'Veterinarian'), (2, 'Guest'), (3, 'Clinic Admin'), (4, 'Veterinary Radiologist'), (5, 'Superuser'), (6, 'Pet Owner')], default=1),
        ),
    ]
