"""
Rename Organization -> Clinic, and Organization.centre -> Clinic.name.

Written by hand rather than autogenerated: `makemigrations` reads this as a
drop-and-recreate (CreateModel Clinic + RemoveField organization), which would
delete every clinic row and null every staff link. RenameModel/RenameField
preserve the table and its data.

RenameModel also rewrites the FK references held by other apps' migration
state, so patients/ai_analysis/dicom_gateway only need to rename their own
field names (their FK *columns* are unaffected by the table rename).
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # Every historical migration that references `users.Organization` by name
    # must be applied *before* the model is renamed, or replaying history on a
    # fresh database fails with "Related model 'users.organization' cannot be
    # resolved". An existing database never hits this — the old migrations are
    # already applied — so it only shows up on a clean install (i.e. CI).
    dependencies = [
        ('users', '0013_alter_user_role'),
        ('patients', '0008_message'),
        ('dicom_gateway', '0004_enhance_pacs_config_with_api_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the index first: it names the old field, and RenameField would
        # otherwise leave the state referring to a column that no longer exists.
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_organiz_7ecef8_idx',
        ),

        migrations.RenameModel(old_name='Organization', new_name='Clinic'),
        migrations.RenameField(model_name='clinic', old_name='centre', new_name='name'),
        migrations.RenameField(model_name='userprofile', old_name='organization', new_name='clinic'),

        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.ForeignKey(
                help_text='Account that created this clinic. Not used for access control.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_clinics',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clinic',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='staff',
                to='users.clinic',
            ),
        ),

        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='users_clini_name_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(
                fields=['clinic', 'is_sharing_jobs_with_colleagues', 'department'],
                name='users_userp_clinic__74fd18_idx',
            ),
        ),
    ]
