# Generated by Django 5.2.17 on 2026-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_organization_to_clinic'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinic',
            new_name='users_clini_name_ec26e6_idx',
            old_name='users_clini_name_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_sharing_jobs_with_colleagues',
            field=models.BooleanField(db_index=True, default=True, help_text='Allow colleagues in same clinic to view your analysis jobs'),
        ),
    ]
