# Generated by Django 5.2.17 on 2026-09-02 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_users_clini_name_idx_users_clini_name_ec26e6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.PositiveBigIntegerField(choices=[(1, 'Veterinarian'), (2, 'Guest'), (3, 'Clinic Admin'), (4, 'Veterinary Radiologist'), (5, 'Superuser'), (6, 'Pet Owner')], default=1)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.clinic')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', '-created_at'], name='users_clini_clinic__2b8b6f_idx'), models.Index(fields=['email'], name='users_clini_email_ab4d68_idx')],
            },
        ),
    ]
