# Generated by Django 5.2.17 on 2026-09-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_clinic_founders_are_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Stable identifier used in code, e.g. 'practice'.", max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('seat_limit', models.PositiveIntegerField(blank=True, help_text='Maximum active members. Null = unlimited.', null=True)),
                ('monthly_analysis_quota', models.PositiveIntegerField(blank=True, help_text='AI analyses per calendar month. Null = unlimited.', null=True)),
                ('storage_bytes', models.BigIntegerField(blank=True, help_text='Total stored image bytes. Null = unlimited.', null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of FEATURE_* flags this plan grants.')),
                ('is_public', models.BooleanField(default=True, help_text='Offered to new clinics. False keeps a plan usable by the clinics already on it without listing it as an option — which is how existing customers were grandfathered.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Subscription tier. Null means unlimited (no plan assigned).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='users.plan'),
        ),
    ]
